title: Site

sections:
  pages:
    type: pages
    create: default
    layout: cards

  plugin_fields:
    type: fields
    fields:
      doctor:
        type: doctor
        label: Perform checks
  
      # colorextractor:
      #  label: Color extractor
      #  type: colorextractor

  # posts:
  #   type: fields
  #   fields:
  #     featured_works:
  #       label: Latest works
  #       type: pages
  #       options: query
  #       query: page.find("works").children
